# AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app-name

  Optional sample SAM template description for sam-app-name

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
  # Resources in a SAM template tend to have shared configuration 
  # such as Runtime, Memory, VPC Settings, Environment Variables, 
  # Cors, etc. Instead of duplicating this information in every 
  # resource, you can write them once in the Globals section and let 
  # all resources inherit it.   CAN BE OVERRIDDEN
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

  NumberFromLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler2
      Runtime: python3.9
      Events:
        NFLF: 
          Type: Api
          Properties:
            Path: /number
            Method: get

  Student:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: Student
      # AttributeDefinitions:
      #   - AttributeName: id
      #     AttributeType: S
      # KeySchema:
      #   - AttributeName: firstName
      #     KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  CreateStudent:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.createStudent
      Runtime: python3.9
      Events:
        CreateStudent:
          Type: Api
          Properties:
            Path: /createStudent
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Student

  GetStudent:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.handler_create
      Runtime: python3.9
      Events:
        CreateStudent:
          Type: Api
          Properties:
            Path: /getStudent
            Method: get
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Student
  
  UpdateStudent:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.handler_create
      Runtime: python3.9
      Events:
        CreateStudent:
          Type: Api
          Properties:
            Path: /updateStudent
            Method: put
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Student

  DeleteStudent:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.handler_create
      Runtime: python3.9
      Events:
        CreateStudent:
          Type: Api
          Properties:
            Path: /deleteStudent
            Method: delete
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Student  

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  CreateStudent:
    Description: "Api for createStudent"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/createStudent"
